"""Local, transparent explanations for filesystem entries."""

from __future__ import annotations

from datetime import datetime

from .models import ItemInfo


RULES: tuple[tuple[set[str], str], ...] = (
    ({"__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache"}, "Python tool cache; it is regenerated when the related tools run."),
    ({"node_modules", ".next", ".nuxt", "dist", "build", "coverage"}, "JavaScript project dependencies or generated build output; it can usually be recreated from the project files."),
    ({".gradle", "target", "bin", "obj"}, "Build-tool output or cache; it is normally regenerated by the project build."),
    ({"cache", "caches", "temp", "tmp"}, "Temporary or cached application data; it may be safe to remove after the associated app is closed."),
    ({"downloads"}, "A downloads folder; inspect its contents because it often contains personal installers and documents."),
)

EXTENSIONS = {
    ".zip": "Compressed archive; it may be an installer, backup, or downloaded bundle.",
    ".msi": "Windows installer package.",
    ".exe": "Windows executable; keep it only if you need the installer or program file.",
    ".log": "Log file recording activity or errors; often removable after troubleshooting.",
    ".tmp": "Temporary file; usually safe only when the creating application is closed.",
    ".py": "Python source code file.",
    ".json": "JSON data or configuration file; inspect its parent project before removing it.",
}


def human_size(size: int) -> str:
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if size < 1024 or unit == "TB":
            return f"{size:.0f} {unit}" if unit == "B" else f"{size:.1f} {unit}"
        size /= 1024
    return f"{size} B"


def explain(item: ItemInfo) -> str:
    """Return a brief, evidence-based explanation for an entry."""
    name = item.path.name.lower()
    for names, message in RULES:
        if name in names:
            return message
    if not item.is_dir and item.path.suffix.lower() in EXTENSIONS:
        return EXTENSIONS[item.path.suffix.lower()]
    if item.is_dir and item.sample:
        sample_lower = {entry.lower() for entry in item.sample}
        if "package.json" in sample_lower:
            return "JavaScript/Node.js project folder, identified by package.json. Do not remove it if you use the project."
        if {"pyproject.toml", "requirements.txt", "setup.py"} & sample_lower:
            return "Python project folder, identified by its dependency or build files. Do not remove it if you use the project."
        if any(entry.endswith((".sln", ".csproj")) for entry in sample_lower):
            return "Visual Studio/.NET project folder, identified by its solution or project files."
        return f"Folder containing items such as {', '.join(item.sample[:4])}. Its exact purpose is not clear from the name alone."
    if item.is_dir:
        return "Folder with no immediately visible contents. It may be empty or contain inaccessible items."
    modified = datetime.fromtimestamp(item.modified_timestamp).strftime("%Y-%m-%d")
    return f"Regular file with no recognizable application signature (modified {modified}). Check whether you created or use it."
