"""Local, transparent explanations for filesystem entries.

This module intentionally does not delete anything and does not use AI.
It identifies common filesystem items using their names, extensions,
locations, and directory contents.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from .models import ItemInfo


# ---------------------------------------------------------------------------
# Directory names
# ---------------------------------------------------------------------------

DIRECTORY_RULES: dict[str, str] = {
    # Python
    "__pycache__": (
        "Python bytecode cache. Python recreates this directory automatically "
        "when the associated program runs."
    ),
    ".pytest_cache": (
        "pytest cache. It contains temporary information used by the Python "
        "testing framework and can be regenerated."
    ),
    ".mypy_cache": (
        "MyPy type-checking cache. It is generated by MyPy and can be "
        "regenerated."
    ),
    ".ruff_cache": (
        "Ruff linting cache. It is generated by Ruff and can be regenerated."
    ),
    ".tox": (
        "Tox test-environment directory. It contains generated test "
        "environments and can usually be recreated."
    ),
    ".nox": (
        "Nox test-environment directory. It contains generated test "
        "environments and can usually be recreated."
    ),
    ".venv": (
        "Python virtual environment. It contains an isolated Python "
        "installation and project dependencies."
    ),
    "venv": (
        "Python virtual environment. It contains an isolated Python "
        "installation and project dependencies."
    ),
    "env": (
        "Potential Python virtual environment. Check its contents before "
        "removing it."
    ),

    # JavaScript / Node
    "node_modules": (
        "Node.js dependency directory. Its contents are installed from "
        "package.json/package-lock.json and can normally be recreated with "
        "the project's package manager."
    ),
    ".npm": (
        "npm cache or configuration directory. Some contents can be "
        "regenerated, but the exact location and contents should be checked."
    ),
    ".yarn": (
        "Yarn project/cache data. Some contents are generated and can be "
        "recreated, but project configuration may also be present."
    ),
    ".pnpm-store": (
        "pnpm package store containing downloaded package data. Packages can "
        "usually be downloaded again if removed."
    ),
    ".next": (
        "Next.js generated build/cache directory. It can normally be "
        "regenerated by building or running the project."
    ),
    ".nuxt": (
        "Nuxt generated build/cache directory. It can normally be "
        "regenerated by the project."
    ),
    ".turbo": (
        "Turborepo cache. It contains generated build information and can "
        "normally be regenerated."
    ),
    ".parcel-cache": (
        "Parcel build cache. It is generated by Parcel and can normally be "
        "regenerated."
    ),
    ".cache": (
        "Generic application or development cache directory. Its contents "
        "may be disposable, but the exact application should be identified."
    ),

    # Build systems
    "build": (
        "Generic build-output directory. It commonly contains files "
        "generated from source code and can often be recreated."
    ),
    "dist": (
        "Distribution/build-output directory. It commonly contains generated "
        "application files."
    ),
    "target": (
        "Build-output directory commonly used by Java, Rust, and other "
        "development tools. Its contents can often be regenerated."
    ),
    "bin": (
        "Binary/build-output directory. It may contain generated program "
        "files, but some applications also store important executables here."
    ),
    "obj": (
        ".NET/MSBuild intermediate build directory. Its contents are normally "
        "generated during a build."
    ),
    "coverage": (
        "Code-coverage output directory. Coverage reports are generated from "
        "tests and can normally be recreated."
    ),

    # Git / development metadata
    ".git": (
        "Git repository metadata. It contains the repository's history, "
        "branches, configuration, and other version-control information."
    ),
    ".hg": (
        "Mercurial repository metadata containing version-control history "
        "and configuration."
    ),
    ".svn": (
        "Subversion metadata used for version control."
    ),
    ".idea": (
        "JetBrains IDE project metadata. It contains IDE configuration and "
        "project settings."
    ),
    ".vscode": (
        "Visual Studio Code workspace/project configuration."
    ),

    # Browsers
    "cache": (
        "Browser or application cache directory. Cached data is generally "
        "regenerable, although the associated application may need to be "
        "closed first."
    ),
    "caches": (
        "Application cache directory. Cached data is generally regenerable."
    ),

    # Temporary
    "temp": (
        "Temporary-data directory. Its contents may be disposable after the "
        "associated applications have been closed."
    ),
    "tmp": (
        "Temporary-data directory. Its contents may be disposable after the "
        "associated applications have been closed."
    ),

    # Common application data
    "logs": (
        "Application log directory. Logs record program activity and errors "
        "and are often safe to remove when no longer needed."
    ),
    "log": (
        "Application log directory. Logs record program activity and errors."
    ),
    "crashdumps": (
        "Crash-dump directory containing diagnostic data generated after "
        "application failures."
    ),
    "crash dumps": (
        "Crash-dump directory containing diagnostic data generated after "
        "application failures."
    ),
    "dump": (
        "Potential diagnostic or crash-dump directory. Check its contents "
        "before removing it."
    ),

    # User data
    "downloads": (
        "Downloads directory. It commonly contains installers, documents, "
        "archives, and other user-downloaded files, so its contents should "
        "be reviewed individually."
    ),
    "documents": (
        "Documents directory. This commonly contains user-created data and "
        "should not be removed without reviewing its contents."
    ),
    "pictures": (
        "Pictures directory containing potentially irreplaceable user data."
    ),
    "videos": (
        "Videos directory containing potentially irreplaceable user data."
    ),
    "music": (
        "Music directory containing potentially irreplaceable user data."
    ),
    "desktop": (
        "Desktop directory. Files here are commonly user-created or "
        "user-selected and should be reviewed individually."
    ),

    # Games
    "shadercache": (
        "Graphics shader cache. Shaders can normally be regenerated by the "
        "game or graphics driver."
    ),
    "shader cache": (
        "Graphics shader cache. Shaders can normally be regenerated."
    ),
}


# ---------------------------------------------------------------------------
# File extensions
# ---------------------------------------------------------------------------

EXTENSION_RULES: dict[str, str] = {
    # Temporary / diagnostic
    ".tmp": (
        "Temporary file. It may be safe to remove after the application that "
        "created it has been closed."
    ),
    ".temp": (
        "Temporary file. It may be safe to remove after the creating "
        "application has been closed."
    ),
    ".log": (
        "Log file containing application or system activity. It is often "
        "safe to remove when no longer needed for troubleshooting."
    ),
    ".dmp": (
        "Crash or memory dump. It may contain diagnostic information useful "
        "for troubleshooting but is generally not required for normal use."
    ),
    ".mdmp": (
        "Windows/minidump diagnostic file generated after an application "
        "crash."
    ),
    ".etl": (
        "Windows Event Trace Log. It contains diagnostic or tracing data."
    ),
    ".wer": (
        "Windows Error Reporting data generated after an application or "
        "system problem."
    ),

    # Archives
    ".zip": (
        "ZIP archive. It may contain an installer, backup, downloaded files, "
        "or other user data."
    ),
    ".7z": (
        "7-Zip archive. It may contain an installer, backup, downloaded files, "
        "or other user data."
    ),
    ".rar": (
        "RAR archive. It may contain an installer, backup, downloaded files, "
        "or other user data."
    ),
    ".tar": (
        "TAR archive commonly used for software distributions and backups."
    ),
    ".gz": (
        "Gzip-compressed file, commonly used for software distributions, "
        "logs, and archives."
    ),
    ".bz2": (
        "Bzip2-compressed file, commonly used for software distributions "
        "and archives."
    ),
    ".xz": (
        "XZ-compressed file, commonly used for software distributions."
    ),

    # Windows installers / executables
    ".exe": (
        "Windows executable program. It may be an installed application, "
        "portable program, installer, updater, or user-downloaded executable."
    ),
    ".msi": (
        "Windows Installer package. It is commonly used to install or repair "
        "Windows software."
    ),
    ".msix": (
        "MSIX Windows application package."
    ),
    ".appx": (
        "APPX Windows application package."
    ),
    ".bat": (
        "Windows batch script capable of executing commands."
    ),
    ".cmd": (
        "Windows command script capable of executing commands."
    ),
    ".ps1": (
        "PowerShell script capable of executing commands on the system."
    ),
    ".com": (
        "Legacy Windows/DOS executable file."
    ),
    ".dll": (
        "Windows dynamic-link library used by applications. It should not "
        "normally be removed individually."
    ),
    ".sys": (
        "Windows/system driver or system component. Do not remove it unless "
        "you know exactly what it belongs to."
    ),

    # Shortcuts
    ".lnk": (
        "Windows shortcut. Removing it normally removes only the shortcut, "
        "not the target application or file."
    ),
    ".url": (
        "Internet shortcut containing a web address."
    ),

    # Source code
    ".py": "Python source code.",
    ".pyw": "Python Windows GUI source code.",
    ".pyi": "Python type-stub source file.",
    ".js": "JavaScript source code.",
    ".jsx": "JavaScript/React source code.",
    ".ts": "TypeScript source code.",
    ".tsx": "TypeScript/React source code.",
    ".html": "HTML source/webpage.",
    ".htm": "HTML source/webpage.",
    ".css": "CSS stylesheet.",
    ".scss": "Sass stylesheet source.",
    ".java": "Java source code.",
    ".kt": "Kotlin source code.",
    ".kts": "Kotlin script/source file.",
    ".c": "C source code.",
    ".h": "C/C++ header/source interface file.",
    ".cpp": "C++ source code.",
    ".cc": "C++ source code.",
    ".cxx": "C++ source code.",
    ".hpp": "C++ header/source interface file.",
    ".cs": "C# source code.",
    ".csx": "C# script source code.",
    ".fs": "F# source code.",
    ".fsx": "F# script source code.",
    ".go": "Go source code.",
    ".rs": "Rust source code.",
    ".swift": "Swift source code.",
    ".rb": "Ruby source code.",
    ".php": "PHP source code.",
    ".lua": "Lua source code.",
    ".sh": "Shell script.",
    ".sql": "SQL source/query file.",

    # Project / build configuration
    ".sln": (
        "Visual Studio solution file containing references to one or more "
        "projects."
    ),
    ".csproj": (
        ".NET/C# project file describing project configuration and "
        "dependencies."
    ),
    ".fsproj": (
        "F#/.NET project file."
    ),
    ".vcxproj": (
        "Visual Studio C/C++ project file."
    ),
    ".gradle": (
        "Gradle build configuration."
    ),
    ".gradlew": (
        "Gradle wrapper script."
    ),
    ".pom": (
        "Maven project metadata/build configuration."
    ),
    ".cmake": (
        "CMake build configuration."
    ),
    ".make": (
        "Make/build configuration file."
    ),
    ".csproj.user": (
        "User-specific Visual Studio project settings."
    ),

    # Configuration / data
    ".json": (
        "JSON data or configuration file. Its importance depends on the "
        "application or project that owns it."
    ),
    ".jsonc": (
        "JSON-with-comments configuration file."
    ),
    ".yaml": (
        "YAML configuration or data file."
    ),
    ".yml": (
        "YAML configuration or data file."
    ),
    ".toml": (
        "TOML configuration file, commonly used by development tools."
    ),
    ".ini": (
        "INI configuration file used by applications."
    ),
    ".cfg": (
        "Configuration file. Its importance depends on the application that "
        "owns it."
    ),
    ".conf": (
        "Configuration file used by an application or service."
    ),
    ".config": (
        "Application configuration file. It may be required for the "
        "associated software to operate correctly."
    ),
    ".env": (
        "Environment-variable configuration file. It may contain application "
        "settings or credentials and should not be removed casually."
    ),
    ".xml": (
        "XML data or configuration file."
    ),

    # Databases
    ".db": (
        "Database file. It may contain application state or user data and "
        "should not be removed without identifying its owner."
    ),
    ".sqlite": (
        "SQLite database. It may contain application state or user data."
    ),
    ".sqlite3": (
        "SQLite database. It may contain application state or user data."
    ),
    ".mdb": (
        "Microsoft Access database."
    ),
    ".accdb": (
        "Microsoft Access database."
    ),
    ".bak": (
        "Backup file. It may be disposable, but it may also be the only "
        "remaining copy of important data."
    ),

    # Documents
    ".txt": "Plain-text document.",
    ".md": "Markdown document.",
    ".rtf": "Rich Text Format document.",
    ".doc": "Microsoft Word document.",
    ".docx": "Microsoft Word document.",
    ".xls": "Microsoft Excel spreadsheet.",
    ".xlsx": "Microsoft Excel spreadsheet.",
    ".ppt": "Microsoft PowerPoint presentation.",
    ".pptx": "Microsoft PowerPoint presentation.",
    ".pdf": "PDF document.",
    ".csv": "Comma-separated data file.",
    ".epub": "Electronic publication/e-book.",

    # Images
    ".jpg": "JPEG image.",
    ".jpeg": "JPEG image.",
    ".png": "PNG image.",
    ".gif": "GIF image.",
    ".bmp": "Bitmap image.",
    ".webp": "WebP image.",
    ".svg": "SVG vector image.",
    ".ico": "Windows/icon image.",
    ".tif": "TIFF image.",
    ".tiff": "TIFF image.",
    ".raw": "Potential raw image/data file; its exact format depends on the source.",

    # Audio
    ".mp3": "MP3 audio file.",
    ".wav": "WAV audio file.",
    ".flac": "FLAC lossless audio file.",
    ".ogg": "OGG audio/container file.",
    ".m4a": "M4A audio file.",
    ".aac": "AAC audio file.",
    ".opus": "Opus audio file.",

    # Video
    ".mp4": "MP4 video file.",
    ".mkv": "Matroska video/container file.",
    ".avi": "AVI video file.",
    ".mov": "QuickTime/MOV video file.",
    ".wmv": "Windows Media video file.",
    ".webm": "WebM video/container file.",
    ".m4v": "M4V video file.",

    # 3D / game assets
    ".obj": "3D model file.",
    ".fbx": "3D model/scene file.",
    ".blend": "Blender project file.",
    ".unity": "Unity project/scene-related file.",
    ".uasset": "Unreal Engine asset file.",
    ".pak": (
        "Package/archive file commonly used by applications and games. "
        "It may contain required program or game assets."
    ),

    # Fonts
    ".ttf": "TrueType font file.",
    ".otf": "OpenType font file.",
    ".woff": "Web font file.",
    ".woff2": "Compressed web font file.",

    # Virtual machines / disk images
    ".iso": (
        "ISO disk image. It may contain an operating-system installer, "
        "software, or backup."
    ),
    ".img": "Disk image or other binary image file.",
    ".vhd": "Virtual hard disk image.",
    ".vhdx": "Hyper-V virtual hard disk image.",
    ".vmdk": "VMware virtual disk image.",
    ".ova": "Virtual appliance archive.",
    ".ovf": "Virtual machine appliance configuration.",

    # Certificates / keys
    ".cer": "Digital certificate.",
    ".crt": "Digital certificate.",
    ".pem": "Certificate/key or other PEM-encoded security data.",
    ".key": "Potential cryptographic key or application key file.",
    ".pfx": "PKCS#12 certificate/private-key container.",
    ".p12": "PKCS#12 certificate/private-key container.",
}


# ---------------------------------------------------------------------------
# Special filename rules
# ---------------------------------------------------------------------------

FILENAME_RULES: dict[str, str] = {
    "desktop.ini": (
        "Windows folder customization metadata. It is normally regenerated "
        "by Windows when needed."
    ),
    "thumbs.db": (
        "Legacy Windows thumbnail cache database. Windows can regenerate it."
    ),
    "ehthumbs.db": (
        "Legacy Windows media thumbnail cache database."
    ),
    ".ds_store": (
        "macOS Finder metadata file. It is not normally needed on Windows."
    ),
    "npm-debug.log": (
        "npm diagnostic log file generated after npm activity or errors."
    ),
    "yarn-debug.log": (
        "Yarn diagnostic log file."
    ),
    "yarn-error.log": (
        "Yarn error log file."
    ),
    "package-lock.json": (
        "npm dependency lockfile. It records exact dependency versions and "
        "should generally be retained with the project."
    ),
    "yarn.lock": (
        "Yarn dependency lockfile. It records exact dependency versions."
    ),
    "pnpm-lock.yaml": (
        "pnpm dependency lockfile. It records exact dependency versions."
    ),
    "cargo.lock": (
        "Rust Cargo dependency lockfile."
    ),
    "poetry.lock": (
        "Python Poetry dependency lockfile."
    ),
    "requirements.txt": (
        "Python dependency list. It is normally part of a Python project."
    ),
    "pyproject.toml": (
        "Python project/build configuration file."
    ),
    "dockerfile": (
        "Docker image build instructions."
    ),
    ".gitignore": (
        "Git ignore configuration controlling which files Git does not track."
    ),
    ".gitattributes": (
        "Git attributes configuration."
    ),
    ".gitmodules": (
        "Git submodule configuration."
    ),
}


# ---------------------------------------------------------------------------
# Location rules
# ---------------------------------------------------------------------------

LOCATION_RULES: tuple[tuple[str, str], ...] = (
    (
        r"\appdata\local\temp",
        "Windows user temporary application data directory. Files here are commonly temporary and regenerated.",
    ),
    (
        r"\appdata\local\microsoft\windows\inetcache",
        "Windows Internet cache containing cached web resources.",
    ),
    (
        r"\appdata\local\microsoft\edge\user data",
        "Microsoft Edge user-data directory. It contains a mixture of cache, configuration, extensions, history, and user data.",
    ),
    (
        r"\appdata\local\google\chrome\user data",
        "Google Chrome user-data directory. It contains a mixture of cache, configuration, extensions, history, and user data.",
    ),
    (
        r"\appdata\local\mozilla\firefox",
        "Mozilla Firefox user-data directory containing browser profiles, cache, settings, and potentially user data.",
    ),
    (
        r"\appdata\local\nvidia",
        "NVIDIA application/driver data. Some subdirectories are caches while others contain configuration or important application data.",
    ),
    (
        r"\appdata\local\d3dscache",
        "Direct3D shader cache. It can normally be regenerated by Windows/applications.",
    ),
    (
        r"\appdata\local\dxcache",
        "Graphics shader/cache data. It can generally be regenerated.",
    ),
    (
        r"\appdata\local\amd",
        "AMD application/driver data. Some contents are caches while others may contain configuration.",
    ),
    (
        r"\appdata\roaming\npm",
        "npm user-level package/tool directory. Contents may include installed command-line tools and should not be blindly removed.",
    ),
    (
        r"\appdata\local\pip\cache",
        "Python pip download/cache directory. Cached packages can normally be downloaded again.",
    ),
    (
        r"\appdata\local\temp",
        "Windows temporary application-data directory.",
    ),
    (
        r"\windows\temp",
        "Windows system temporary-data directory. Contents are generally temporary, although files currently in use may not be removable.",
    ),
    (
        r"\windows\softwaredistribution\download",
        "Windows Update download cache. Contents can generally be recreated by Windows Update.",
    ),
    (
        r"\windows\prefetch",
        "Windows application prefetch data used to improve application startup performance. Windows can regenerate it.",
    ),
    (
        r"\programdata\microsoft\windows\wer",
        "Windows Error Reporting data used for diagnostics.",
    ),
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def human_size(size: int) -> str:
    """Format a byte count for display."""
    value = float(size)

    for unit in ("B", "KB", "MB", "GB", "TB"):
        if value < 1024 or unit == "TB":
            return f"{value:.0f} {unit}" if unit == "B" else f"{value:.1f} {unit}"
        value /= 1024

    return f"{size} B"


def _project_explanation(item: ItemInfo) -> str | None:
    """Identify common development projects from directory contents."""
    if not item.is_dir:
        return None

    names = {entry.casefold() for entry in item.sample}

    if "package.json" in names:
        return (
            "JavaScript/Node.js project directory identified by package.json. "
            "It may contain source code, dependencies, build output, or "
            "configuration."
        )

    if {
        "pyproject.toml",
        "requirements.txt",
        "setup.py",
        "setup.cfg",
    } & names:
        return (
            "Python project directory identified by its project/dependency "
            "files. It may contain source code and generated environments or caches."
        )

    if any(name.endswith((".sln", ".csproj", ".fsproj", ".vbproj")) for name in names):
        return (
            "Visual Studio/.NET project directory identified by its solution "
            "or project files."
        )

    if "cargo.toml" in names:
        return (
            "Rust project directory identified by Cargo.toml. Build output "
            "and dependency data may be regenerated, but source/configuration "
            "files should be retained."
        )

    if "pom.xml" in names:
        return (
            "Java/Maven project directory identified by pom.xml."
        )

    if "build.gradle" in names or "settings.gradle" in names:
        return (
            "Java/Kotlin Gradle project directory."
        )

    if "dockerfile" in names:
        return (
            "Directory containing a Docker build configuration. It may contain "
            "source code and other files required to build the image."
        )

    return None


def _location_explanation(path: Path) -> str | None:
    """Identify common Windows/application locations."""
    text = str(path.resolve(strict=False)).casefold().replace("/", "\\")

    # Check longer/more-specific paths first.
    matches = sorted(LOCATION_RULES, key=lambda rule: len(rule[0]), reverse=True)

    for fragment, explanation in matches:
        if fragment in text:
            return explanation

    return None


# ---------------------------------------------------------------------------
# Main explanation
# ---------------------------------------------------------------------------

def explain(item: ItemInfo) -> str:
    """Return the best local explanation available for a filesystem item."""

    name = item.path.name.casefold()
    suffix = item.path.suffix.casefold()

    # Exact filename is strongest.
    if name in FILENAME_RULES:
        return FILENAME_RULES[name]

    # Exact directory name.
    if item.is_dir and name in DIRECTORY_RULES:
        return DIRECTORY_RULES[name]

    # Project structure is more useful than generic extension matching.
    project_explanation = _project_explanation(item)
    if project_explanation:
        return project_explanation

    # Application/system location.
    location_explanation = _location_explanation(item.path)
    if location_explanation:
        return location_explanation

    # Extension.
    if not item.is_dir and suffix in EXTENSION_RULES:
        return EXTENSION_RULES[suffix]

    # Generic filename clues.
    if any(word in name for word in ("cache", "cached")):
        return (
            "The filename indicates cached data. Cache files are often "
            "regenerated, but the owning application should be identified first."
        )

    if any(word in name for word in ("temp", "temporary")):
        return (
            "The filename indicates temporary data. It may be safe to remove "
            "after the associated application has been closed."
        )

    if any(word in name for word in ("crash", "dump", "minidump")):
        return (
            "The filename suggests crash or diagnostic data. It may be useful "
            "for troubleshooting but is generally not required for normal operation."
        )

    if "log" in name:
        return (
            "The filename suggests an application log. Logs are generally "
            "diagnostic records and can often be removed when no longer needed."
        )

    if any(word in name for word in ("backup", "bak", "old", "copy")):
        return (
            "The filename suggests a backup, older copy, or duplicate. It "
            "should be reviewed carefully because it may contain the only "
            "remaining copy of important data."
        )

    # Directory with visible contents.
    if item.is_dir:
        if item.sample:
            contents = ", ".join(item.sample[:5])
            return (
                f"Folder containing items such as {contents}. "
                "Its exact purpose cannot be determined from the available "
                "local information."
            )

        return (
            "Folder with no immediately visible contents. It may be empty or "
            "contain inaccessible items."
        )

    # Final fallback.
    try:
        modified = datetime.fromtimestamp(item.modified_timestamp).strftime(
            "%Y-%m-%d"
        )
    except (OSError, ValueError):
        modified = "an unknown date"

    size = human_size(item.size_bytes)

    return (
        f"Regular file ({size}) with no recognizable cleanup signature "
        f"(modified {modified}). Its purpose should be identified before removal."
    )